### ISSUE TITLE
Mesh Topology Issue

### ISSUE THREAD

**Issue by adamfred** [minoslas/DCS_W_Naval_Project#1]
This topology will be a problem. 
![pr204_stern_issue-bad-toplogy](https://cloud.githubusercontent.com/assets/3635953/8879312/0f321da0-3274-11e5-8173-94ba6315b68c.jpg)

Also I have not seen any pictures where the shape of the stern looks like this. Most of the pictures show a shape more like the picture below.

![z_b2521db5_crop](https://cloud.githubusercontent.com/assets/3635953/8879987/95ca3240-3278-11e5-9334-e3cba72ba162.jpg)

**Comment by minoslas** [comment]
Good Point Adam, I see the first drawlines I use to the model has very incorrect, using news to perform a better look

![pr 204_draw_lines](https://cloud.githubusercontent.com/assets/13463671/8880847/ae7059ea-3233-11e5-8a49-41c0f1d5c7fc.png)

**Comment by minoslas** [comment]
Part 1 of the Pr.204 reconstruction
![pr 204_reconstruction_2](https://cloud.githubusercontent.com/assets/13463671/8956425/c26e25f4-35ed-11e5-9975-85ed79843842.JPG)

**Comment by minoslas** [comment]
Bow part of the Pr.204
![pr 204_reconstruction_3](https://cloud.githubusercontent.com/assets/13463671/8957592/5fc9a306-35f7-11e5-8e0e-56762e1d43c8.JPG)

**Comment by minoslas** [comment]
![pr 204_reconstruction_4](https://cloud.githubusercontent.com/assets/13463671/8960709/4117a888-3609-11e5-80b5-d02691033b98.JPG)

**Comment by minoslas** [comment]
I think with them, the external hulk rework has been complet, send you the 3D model.
![pr 204_reconstruction_5](https://cloud.githubusercontent.com/assets/13463671/8962293/b95cfc50-3611-11e5-81cc-abd6544ab30f.JPG)
